### ISSUE TITLE
Design UI for bid and sell offers.

### ISSUE THREAD

**Issue by paeljojy** [paeljojy/StockBrokerage#4]
For reference: Docs/Q4US-Assignment-Continuous-SW-Eng-Uni-Jyvaskyla.pdf

We want to design clean UI for bids and sell offers.

The current description in the assignment is somewhat miss-leading, make this clearer and come up with a concept for easily usable user-interface for add sell and buy offers.

**Comment by Pvscal** [comment]
<img width="566" alt="image" src="https://github.com/paeljojy/StockBrokerage/assets/125104460/05edc228-70db-4d1b-adf4-4e456d886c0c">
https://www.figma.com/file/qttLAEM5OJNjg50w4nOBWi/Untitled?type=design&node-id=0%3A1&mode=dev&t=spISAnFQ19OOTOkn-1
